import { Client, Deal } from '../types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli_1',
    name: 'Roberto Alencar',
    type: 'contact',
    email: 'roberto.alencar@techsolucoes.com',
    phone: '(11) 98765-4321',
    companyName: 'Tech Soluções',
    role: 'Diretor de TI',
    notes: 'Cliente em busca de migrar para nuvem e procura soluções Enterprise.',
    createdAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'cli_2',
    name: 'Juliana Ferreira',
    type: 'contact',
    email: 'juliana.f@construtoravancouver.com',
    phone: '(21) 99888-2233',
    companyName: 'Vancouver Engenharia',
    role: 'Gerente de Suprimentos',
    notes: 'Interesse em softwares de automação de obras e RH.',
    createdAt: '2026-05-12T14:30:00Z',
  },
  {
    id: 'cli_3',
    name: 'Vancouver Engenharia',
    type: 'company',
    email: 'contato@vancouverengenharia.com',
    phone: '(21) 3344-5566',
    revenue: 'R$ 15.200.000,00',
    notes: 'Grande construtora com projetos residenciais no Rio e São Paulo.',
    createdAt: '2026-05-12T14:35:00Z',
  },
  {
    id: 'cli_4',
    name: 'Tech Soluções de TI',
    type: 'company',
    email: 'atendimento@techsolucoes.com',
    phone: '(11) 5099-8800',
    revenue: 'R$ 4.500.000,00',
    notes: 'Focados em terceirização e infraestrutura de TI.',
    createdAt: '2026-05-10T09:45:00Z',
  },
  {
    id: 'cli_5',
    name: 'Clínica Sorriso Feliz',
    type: 'company',
    email: 'financeiro@sorrisofeliz.com.br',
    phone: '(31) 3212-0099',
    revenue: 'R$ 1.200.000,00',
    notes: 'Dentistas associados buscando modernização de plataforma de agendamento.',
    createdAt: '2026-05-15T11:20:00Z',
  },
  {
    id: 'cli_6',
    name: 'Dr. Arthur Mendes',
    type: 'contact',
    email: 'arthur.mendes@sorrisofeliz.com.br',
    phone: '(31) 98111-2233',
    companyName: 'Clínica Sorriso Feliz',
    role: 'Sócio-Fundador',
    notes: 'Procura soluções ágeis para marketing digital local e captação de clientes.',
    createdAt: '2026-05-15T11:25:00Z',
  }
];

export const INITIAL_DEALS: Deal[] = [
  {
    id: 'deal_1',
    title: 'Migração AWS & Suporte Cloud',
    clientId: 'cli_1',
    stage: 'Prospect',
    value: 85000,
    probability: 20,
    description: 'Mudança de infraestrutura on-premise para a nuvem da AWS. Requer 12 meses de suporte gerenciado.',
    createdAt: '2026-05-11T09:00:00Z',
    updatedAt: '2026-05-11T09:00:00Z',
    assignedTo: 'SAMAYER Whatsapp',
    tags: ['Cloud', 'Enterprise', 'AWS']
  },
  {
    id: 'deal_2',
    title: 'Licenciamento de Software ERP',
    clientId: 'cli_3',
    stage: 'Proposal',
    value: 120000,
    probability: 50,
    description: 'Proposta de ERP customizado para gerenciamento de insumos e folha de pagamento na Vancouver Engenharia.',
    createdAt: '2026-05-13T10:15:00Z',
    updatedAt: '2026-05-15T16:30:00Z',
    assignedTo: 'SAMAYER Whatsapp',
    tags: ['ERP', 'Licenças', 'Construção']
  },
  {
    id: 'deal_3',
    title: 'Consultoria de Processos Organizacionais',
    clientId: 'cli_2',
    stage: 'Negotiation',
    value: 45000,
    probability: 70,
    description: 'Ajustes e melhorias em fluxos de RH e contábeis. Proposta enviada, em negociação de prazo de entrega.',
    createdAt: '2026-05-14T08:30:00Z',
    updatedAt: '2026-05-20T11:00:00Z',
    assignedTo: 'SAMAYER Whatsapp',
    tags: ['Consultoria', 'RH']
  },
  {
    id: 'deal_4',
    title: 'Software de Agendamento Sorriso Feliz',
    clientId: 'cli_5',
    stage: 'Invoice',
    value: 18000,
    probability: 90,
    description: 'Desenvolvimento e setup inicial de app de reservas e fidelidade. Fatura enviada, aguardando compensação do sinal.',
    createdAt: '2026-05-16T15:00:00Z',
    updatedAt: '2026-05-24T10:00:00Z',
    assignedTo: 'SAMAYER Whatsapp',
    tags: ['Saas', 'Dental']
  },
  {
    id: 'deal_5',
    title: 'Implementação de CRM Customizado',
    clientId: 'cli_1',
    stage: 'Won',
    value: 64000,
    probability: 100,
    description: 'Contrato assinado para parametrização do CRM interna da Tech Soluções de TI.',
    createdAt: '2026-05-12T11:00:00Z',
    updatedAt: '2026-05-22T17:00:00Z',
    assignedTo: 'SAMAYER Whatsapp',
    tags: ['CRM', 'Ganho']
  },
  {
    id: 'deal_6',
    title: 'Marketing Digital Clínica Odonto',
    clientId: 'cli_6',
    stage: 'Negotiation',
    value: 12000,
    probability: 60,
    description: 'Gestão de tráfego pago (Google/Meta Ads) pelo período de 3 meses para a clínica local.',
    createdAt: '2026-05-18T12:00:00Z',
    updatedAt: '2026-05-23T14:00:00Z',
    assignedTo: 'SAMAYER Whatsapp',
    tags: ['Trafego Pago', 'Marketing']
  }
];
